import { z } from "zod";

export const quizSchema = z.object({
  companyName: z.string().min(2, "Inserisci la ragione sociale"),
  vat: z.string().min(5, "Inserisci P.IVA o CF"),
  sector: z.string().min(2, "Seleziona il settore"),
  address: z.string().min(3, "Inserisci l'indirizzo"),
  city: z.string().min(2, "Inserisci la citta"),
  province: z.string().min(2, "Inserisci la provincia"),
  postalCode: z.string().regex(/^\d{5}$/, "CAP non valido"),
  locations: z.string().min(1, "Seleziona il numero di sedi"),
  peoplePrinting: z.string().min(1, "Seleziona quante persone stampano"),
  monthlyVolume: z.string().min(1, "Seleziona un volume"),
  colorMix: z.string().min(1, "Seleziona la percentuale colore"),
  formats: z.array(z.string()).min(1, "Seleziona almeno un formato"),
  printersNeeded: z.string().min(1, "Seleziona il numero di stampanti"),
  distribution: z.string().min(1, "Seleziona la distribuzione"),
  functions: z.array(z.string()).min(1, "Seleziona almeno una funzione"),
  priorities: z.array(z.string()).min(1, "Seleziona almeno una priorita").max(2, "Seleziona massimo due priorita"),
  documentTypes: z.array(z.string()).optional(),
  modelPreference: z.string().min(1, "Seleziona una preferenza"),
  modelNote: z.string().optional(),
  contactName: z.string().min(2, "Inserisci nome e cognome"),
  role: z.string().min(2, "Inserisci il ruolo"),
  email: z.string().email("Email non valida"),
  phone: z.string().min(6, "Inserisci un telefono valido"),
  contactPreference: z.string().min(1, "Seleziona una preferenza"),
  note: z.string().optional(),
  consentPrivacy: z.boolean().refine((v) => v === true, "Consenso privacy richiesto"),
  consentMarketing: z.boolean().optional(),
});

export type QuizFormValues = z.infer<typeof quizSchema>;

export const quizDefaults: QuizFormValues = {
  companyName: "",
  vat: "",
  sector: "",
  address: "",
  city: "",
  province: "",
  postalCode: "",
  locations: "",
  peoplePrinting: "",
  monthlyVolume: "",
  colorMix: "",
  formats: [],
  printersNeeded: "",
  distribution: "",
  functions: [],
  priorities: [],
  documentTypes: [],
  modelPreference: "",
  modelNote: "",
  contactName: "",
  role: "",
  email: "",
  phone: "",
  contactPreference: "",
  note: "",
  consentPrivacy: false,
  consentMarketing: false,
};

export const quizSteps = [
  { id: 1, title: "Conosciamoci meglio", fields: [
    "companyName",
    "vat",
    "sector",
    "address",
    "city",
    "province",
    "postalCode",
    "locations",
    "peoplePrinting",
  ] },
  { id: 2, title: "Quanto stampi", fields: ["monthlyVolume", "colorMix", "formats"] },
  { id: 3, title: "Quante stampanti", fields: ["printersNeeded", "distribution", "functions"] },
  { id: 4, title: "Qualita e utilizzo", fields: ["priorities", "documentTypes"] },
  { id: 5, title: "Preferenze modello", fields: ["modelPreference", "modelNote"] },
  { id: 6, title: "Contatti", fields: [
    "contactName",
    "role",
    "email",
    "phone",
    "contactPreference",
    "note",
    "consentPrivacy",
    "consentMarketing",
  ] },
];
